#enable all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: *
        
#enable eureka path to other services
eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:8761/
    
